version: "3"

services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   env_file:
  #     - ./.env
  #   networks:
  #     - todo_app_network
  #   ports:
  #     - "8080:8080"
  #   restart: always

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./packages/database/volumes:/var/lib/postgresql/data
    # networks:
    #   - todo_app_network

  # web:
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   env_file:
  #     - ./.env
  #   networks:
  #     - todo_app_network
  #   ports:
  #     - '8081:8081'
  #   restart: always

volumes:
  postgres_data:
# networks:
#   todo_app_network:
#     driver: bridge
